### ISSUE TITLE
App switcher screenshot

### ISSUE THREAD

**Issue by apm-lucas-zacharias** [velikanov/SwiftPasscodeLock#19]
First of all thank you. This is a great project I really like it.
But I have a problem with the screenshot in the app switcher. 
It only shows a white screen (not even the numpad). 
I would like to show the user a picture instead of the white screen is this possible?
![image](https://cloud.githubusercontent.com/assets/8128416/13906521/6f71de5a-eed8-11e5-8ba6-21c695f59eef.jpeg)

**Comment by ziogaschr** [comment]
Have you copied code like [this](https://github.com/velikanov/SwiftPasscodeLock/blob/master/PasscodeLockDemo/CustomPasscodeLockPresenter.swift#L86-L102) from the demo's code?

If yes then this is the reason you are getting this white `Splash view`. Normally it will have an icon too, but probably you haven't copied too to your assets.

By following the SplashView logic you can create any image you like.

I will close your issue, but if this doesn't solve it, then please re-open it.
