### ISSUE TITLE
inccorectPasscodeAttempts value not persisted between app launches

### ISSUE THREAD

**Issue by le4ker** [velikanov/SwiftPasscodeLock#26]
Opened it in the forked [repository](https://github.com/yankodimitrov/SwiftPasscodeLock/issues/56) as well.

> This bug allows to brute force the passcode lock by quitting the app before reaching the maximum > attempts limit and then opening the app again.
> 
> A solution could be to store the value in the NSUserDefaults or the Keychain.

**Comment by ziogaschr** [comment]
An attempt to show how to fix this has been added in PR #27.
Can you check if this is working for you and close this issue if works?

**Comment by le4ker** [comment]
Hi guys. Any update on this bug? @ziogaschr PR #27 was a correct fix 😄

**Comment by ziogaschr** [comment]
@PanosSakkos I will try to merge PR #27 soon. I have some work at the moment, but I will try to find some time
