### ISSUE TITLE
Swift 3 update

### ISSUE THREAD

**Issue by johisco** [velikanov/SwiftPasscodeLock#39]
Anyone working on it?

**Comment by aalfath** [comment]
+1

**Comment by vitobellini** [comment]
+1

**Comment by aalfath** [comment]
Just an update, I temporarily use another fork made by another user.

Please check the following comment: https://github.com/yankodimitrov/SwiftPasscodeLock/issues/67#issuecomment-252633426

**Comment by ziogaschr** [comment]
Done. Swift 3 support on master branch
