### ISSUE TITLE
no 1.0.3 version available

### ISSUE THREAD

**Issue by ssavic** [velikanov/SwiftPasscodeLock#46]
Swift 3 support is not live.  Pod keeps downloading older 1.0.2 version

**Comment by kurry421** [comment]
I am seeing the same issue :(. Ended up just going to each file on here and copying/pasting to update the pod on my Xcode.  @ssavic

**Comment by ssavic** [comment]
@kurry421 I've done the same thing but I get an error that module compiled with swift 3.0.1 can not be imported into swift 3.1

**Comment by ziogaschr** [comment]
You can use the Podfile by adding this line manually
`pod 'PasscodeLock', :git => 'https://github.com/velikanov/SwiftPasscodeLock.git', :branch => 'master'`

This repo is not the original one and only @yankodimitrov has access to push a new version to the Pod registry. Personally, I use this repo or my own fork.

I am not sure if this can be fixed somehow, whatever it happens, we have to ask for permission from @yankodimitrov, as this is his package and also his awesome contribution to the community.
